apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
    - name: hello
      image: tonnytg/hello:v1.1.0
      ports:
        - containerPort: 8081
          protocol: TCP